name: Artifacts

on:
  pull_request:

jobs:

  test:
    name: Run a demo test
    runs-on: ubuntu-latest
    steps:

      - name: main
        run: |
          mkdir -p artifacts
          cat > artifacts/message.md <<EOF
          $(env | sort)
          EOF
      - name: Save PR message as artifact
        uses: actions/upload-artifact@v1
        with:
          name: pr_message
          path: artifacts
