name: "Close stale issues"
on:
  push:
  
  schedule:
  - cron: "*/10 * * * *"

jobs:
  update_reviewers:
    runs-on: ubuntu-latest

    steps:
      - name: main
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" -H "authorization: Bearer $GITHUB_TOKEN" https://api.github.com/repos/ntampakas/drill-ft/pulls/1/requested_reviewers -d '{"reviewers":["AronisAt79"]}'
